<?php

namespace api\modules\v1\admin\cms\command;

use api\modules\v1\admin\cms\models\Collection;
use common\models\SystemCmsCollection;
use yii\base\Exception;
use yii\db\Migration;
use yii\db\Query;

/**
 * @property SystemCmsCollection $collection
 */
class MigrateColumnCollection extends Migration
{
    protected $prefix = "cms_";
    public $collection;
    public $indexs;

    public function init()
    {
        $this->compact = true;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function getCollectionName($collectionName = "")
    {
        return $this->prefix . ($collectionName ?: $this->collection->name);
    }

    /**
     * @throws Exception
     */
    public function up()
    {
        $this->createTable($this->getCollectionName(), $this->getListColumn());
        $this->createBatchIndex();
    }

    public function down()
    {
        $this->dropTable($this->getCollectionName());
    }

    /**
     * @throws Exception
     */
    public function addOrDropColumns($collectionOlds)
    {
        $collectionNews = $this->collection;
        if ($collectionOlds["name"] != $collectionNews["name"]) {
            $this->renameTable($this->getCollectionName($collectionOlds["name"]), $this->getCollectionName());
        }
        $schemaNews = $this->collection->schemas;
        $schemaOlds = $collectionOlds["schemas"];
        if (is_string($schemaOlds)) {
            $schemaOlds = @json_decode($collectionOlds["schemas"], true);
        }
        foreach ($schemaOlds as $schemaOld) {
            if ($this->isDropSchemaOldAndSetSchemasNew($schemaOld, $schemaNews)) {
                $this->dropColumn($this->getCollectionName(), $schemaOld["name"]);
            }
        }
        foreach ((array)$schemaNews as $schemaNew) {
            $this->addColumn($this->getCollectionName(), $schemaNew["name"], $this->getColumn($schemaNew));
        }
        $this->createBatchIndex();
    }

    /**
     * @param $schemaOld
     * @param $schemaNews
     * @return bool
     */
    protected function isDropSchemaOldAndSetSchemasNew($schemaOld, &$schemaNews): bool
    {
        foreach ($schemaNews as $key => $schemaNew) {
            if ($schemaOld["id"] !== $schemaNew["id"]) {
                continue;
            }
            if ($schemaOld["type"] !== $schemaNew["type"]) {
                return true;
            }
            if ($schemaOld["name"] !== $schemaNew["name"]) {
                $this->renameColumn($this->getCollectionName(), $schemaOld["name"], $schemaNew["name"]);
                unset($schemaNews[$key]);
                return false;
            }
            unset($schemaNews[$key]);
            return false;
        }
        return true;
    }

    public function dropBatchCollection()
    {
        $collections = (new Query())->select("table_name")
            ->from("information_schema.tables")
            ->where(["LIKE", "table_name", "cms_"])
            ->andWhere(["<>", "table_name", "system_cms_collection"])
            ->all();
        foreach ($collections as $collection) {
            $this->dropTable($collection["table_name"]);
        }
    }

    public function createBatchIndex()
    {
        foreach ((array)$this->indexs as $column) {
            $this->createIndex($this->getIndexName($column), $this->getCollectionName(), $column);
        }
    }

    public function getIndexName($column): string
    {
        return "idx-{$this->getCollectionName()}-$column";
    }

    /**
     * @throws Exception
     */
    public function getListColumn(): array
    {
        $columns = [
            "id" => $this->primaryKey()
        ];
        foreach ((array)$this->collection->schemas as $schema) {
            $columns[$schema["name"]] = $this->getColumn($schema);
        }
        $columns["created_at"] = $this->dateTime();
        $columns["updated_at"] = $this->dateTime();
        return $columns;
    }

    /**
     * @throws Exception
     */
    public function getColumn($schema)
    {
        switch ($schema["type"]) {
            case SystemCmsCollection::TYPE_FILE:
            case SystemCmsCollection::TYPE_URL:
            case SystemCmsCollection::TYPE_SLUG:
            case SystemCmsCollection::TYPE_TEXT:
                return $this->string(500);
            case SystemCmsCollection::TYPE_BOOLEAN:
                return $this->boolean();
            case SystemCmsCollection::TYPE_EDITOR:
                return $this->text();
            case SystemCmsCollection::TYPE_DATE_TIME:
                return $this->dateTime();
            case SystemCmsCollection::TYPE_JSON:
            case SystemCmsCollection::TYPE_SELECT:
                return $this->json();
            case SystemCmsCollection::TYPE_EMAIL:
                return $this->string(100);
            case SystemCmsCollection::TYPE_NUMBER:
                return $this->double();
            case SystemCmsCollection::TYPE_RELATION:
                $this->indexs[] = $schema["name"];
                return $this->string();
            default:
                return $this->string();
        }
    }
}