<?php

namespace api\modules\v1\frontend\cart;

use yii\base\Module;

class CartModule extends Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}