<?php

namespace api\modules\v1\frontend\article;

class ArticleModule extends \yii\base\Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}