<?php

namespace api\modules\v1\frontend\product\models\search;

use common\models\Brand;
use yii\data\ActiveDataProvider;

class BrandSearch extends Brand
{
    /**
     * @return array
     */
    public function fields(): array
    {
        return [
            "id",
            "name",
            "type",
            "code",
            "description",
            "icon",
            "images",
            "color",
            "priority",
            "show_on_home",
            "parent_id"
        ];
    }

    /**
     * @return array
     */
    public function rules(): array
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $params
     * @return BrandSearch|array|Brand|null
     */
    public function searchFind($params)
    {
        $query = self::find()->active();
        $this->load($params, "");
        if (!$this->validate()) {
            return $query->one();
        }
        $query->andFilterWhere($this->filterField());
        return $query->one();
    }

    /**
     * @return array
     */
    private function filterField(): array
    {
        return [
            "id" => $this->id,
            "name" => $this->name,
            "type" => $this->type,
            "code" => $this->code,
            "description" => $this->description,
            "icon" => $this->icon,
            "images" => $this->images,
            "color" => $this->color,
            "show_on_home" => $this->show_on_home
        ];
    }

    public function search($params): ActiveDataProvider
    {
        $query = self::find()->active();
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'params' => $params
            ],
            'sort' => [
                'params' => $params,
                // priority nhỏ hiện trước — cùng quy ước với banner và menu danh mục.
                'defaultOrder' => ['priority' => SORT_ASC, 'id' => SORT_DESC]
            ]
        ]);
        $this->load($params, "");
        if (!$this->validate()) {
            return $dataProvider;
        }
        $query->andFilterWhere($this->filterField());
        return $dataProvider;
    }
}