<?php

namespace api\modules\v1\frontend\product\models\search;

use yii\data\ActiveDataProvider;
use api\modules\v1\frontend\product\models\Category;

class CategorySearch extends Category
{
    /**
     * `1` => trả PHẲNG cả danh mục cha lẫn con (không lồng).
     *
     * Mặc định chỉ trả danh mục gốc kèm `children`; FE cần danh sách phẳng (vd để build
     * breadcrumb hoặc trang "tất cả danh mục") thì gọi `?flat=1`.
     *
     * @var int|string|null
     */
    public $flat;

    public function rules(): array
    {
        return [
            [['id', 'priority', 'show_on_home', 'parent_id', 'status'], 'integer'],
            [['name', 'type', 'code', 'icon', 'images', 'slug', 'flat'], 'safe'],
        ];
    }

    public function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }

    public function search($params): ActiveDataProvider
    {
        $query = Category::find()->active()->with(["children"]);
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'params' => $params
            ],
            'sort' => [
                'params' => $params,
                // priority nhỏ hiện trước — cùng quy ước với banner và menu danh mục.
                'defaultOrder' => ['priority' => SORT_ASC, 'id' => SORT_DESC]
            ]
        ]);

        $this->load($params, "");

        // Mặc định chỉ trả danh mục GỐC, mỗi cái kèm `children`.
        // `?flat=1` lấy phẳng, `?parent_id=44` lấy con của 1 cha.
        if (!$this->flat && ($this->parent_id === null || $this->parent_id === "")) {
            $query->andWhere(["parent_id" => null]);
        }
        if (!$this->validate()) {
            return $dataProvider;
        }
        $query->andFilterWhere([
            'id' => $this->id,
            'priority' => $this->priority,
            'parent_id' => $this->parent_id,
            'name' => $this->name,
            "type" => $this->type,
            "code" => $this->code,
            "icon" => $this->icon,
            "show_on_home" => $this->show_on_home
        ]);
        return $dataProvider;
    }

}