<?php

namespace api\modules\v1\frontend\product\models\search;

use yii\data\ActiveDataProvider;
use api\modules\v1\frontend\product\models\Category;

class CategorySearch extends Category
{
    public function rules(): array
    {
        return [
            [['id', 'priority', 'show_on_home', 'parent_id', 'status'], 'integer'],
            [['name', 'type', 'code', 'icon', 'images','slug'], 'safe'],
        ];
    }

    public function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }

    public function search($params): ActiveDataProvider
    {
        $query = Category::find()->active();
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'params' => $params
            ],
            'sort' => [
                'params' => $params,
                // priority nhỏ hiện trước — cùng quy ước với banner và menu danh mục.
                'defaultOrder' => ['priority' => SORT_ASC, 'id' => SORT_DESC]
            ]
        ]);

        $this->load($params, "");
        if (!$this->validate()) {
            return $dataProvider;
        }
        $query->andFilterWhere([
            'id' => $this->id,
            'priority' => $this->priority,
            'parent_id' => $this->parent_id,
            'name' => $this->name,
            "type" => $this->type,
            "code" => $this->code,
            "icon" => $this->icon,
            "show_on_home" => $this->show_on_home
        ]);
        return $dataProvider;
    }

}