<?php
/**
 * Smart Digitech Co LTD (c) 2016, All right reverse
 * Fast boy Marketing CRM Project
 * Date: 20/12/2018
 * Time: 10:42 AM
 */


namespace common\components\plivo;

use yii\base\InvalidConfigException;
use yii\base\Component;

use Plivo\RestClient;


/**
 * Class Client
 * @package common\components\plivo
 * @property RestClient $client
 * @property string $authID
 * @property string $fromPhone
 */
class Client extends Component
{
    protected $client;
    public $authID;
    public $token;
    public $fromPhone;

    public function init()
    {
        if ($this->authID == null || $this->token == null) {
            throw new InvalidConfigException("Plivo AuthID or Token is invalid!");
        }
        $this->client = new RestClient($this->authID, $this->token);
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $to
     * @param $message
     * @return mixed
     */
    public function sendText($to, $message)
    {
        $message_created = $this->client->messages->create(
            $this->fromPhone,
            (array)$to,
            $message
        );

        return $message_created;
    }

}