<?php

namespace api\modules\v1\frontend\page\models\search;

use yii\data\ActiveDataProvider;

class  PageSearch extends \common\models\Page
{
    public function rules()
    {
        return [
            [["id", "slug", "title", "content", "create_by", "created_at"], "safe"],
            ["id", "integer"],
            [["slug", "title", "content", "create_by"], "string"]
        ];
    }

    public function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }

    public function searchFind($params)
    {
        $query = self::find()->active();
        $this->load($params,"");
        if (!$this->validate()) {
            return $query->one();
        }
        $query->andFilterWhere([
            "id" => $this->id,
            "slug" => $this->slug,
            "title" => $this->title,
            "create_by" => $this->create_by,
            "status" => $this->status
        ]);
        return $query->one();
    }


    public function search($params)
    {
        $query = self::find()->active();
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'params' => $params,
            ],
            'sort' => [
                'params' => $params,
            ],
        ]);
        if (!($this->load($params, "") && $this->validate())) {
            return $dataProvider;
        }
        $query->andFilterWhere([
            "id" => $this->id,
            "slug" => $this->slug,
            "title" => $this->title,
            "create_by" => $this->create_by,
            "status" => $this->status
        ]);
        return $dataProvider;
    }
}