<?php


namespace api\modules;


use yii\filters\Cors;
use yii\filters\VerbFilter;

class Module extends \yii\base\Module
{
    public function init()
    {
        parent::init();
        $this->modules = [
            "v1" => v1\VersionModule::class
        ];
        $this->components = [
            "productInventory" => v1\components\ProductInventory::class
        ];
    }

    public function behaviors(): array
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub

        $behaviors['corsFilter'] = [
            'class' => Cors::class, // the new Cors class inherited from yii2's
            'cors' => [
                'Origin' => ['*'],
                'Access-Control-Request-Method' => ['GET', 'POST', 'OPTIONS'],
                'Access-Control-Request-Headers' => ['Origin', 'X-Requested-With', 'Content-Type', 'accept', 'Authorization','Tenant-ID'],
            ],
        ];

        /* Default Validate Method */
        $behaviors["verbFilter"] = [
            'class' => VerbFilter::className(),
            'actions' => [
                'index' => ['GET'],
                'update' => ['POST'],
                'view' => ['GET'],
                'delete' => ['POST', 'DELETE'],
                'delete-many' => ['POST', 'DELETE'],
                'create' => ['POST']
            ]
        ];
        return $behaviors;
    }
}
