<?php

namespace api\modules\v1\admin\cms\models\form;

use common\validators\cms\IndexValidator;
use Yii;
use api\modules\v1\admin\cms\models\SystemCmsCollection;
use common\validators\cms\SchemaValidator;

class SystemCmsCollectionForm extends SystemCmsCollection
{
    public function beforeSave($insert)
    {
        $this->user_id = Yii::$app->user->getId();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return array_merge(parent::rules(), [
            [["name", "schemas", "type"], "required"],
            ["name", "unique"],
            ["type", "in", "range" => [self::TYPE_AUTH, self::TYPE_BASE]],
            ["schemas", SchemaValidator::class]
        ]);
    }
}