<?php

namespace common\components\log;

use yii\web\ErrorHandler;
use function Sentry\captureException;
use function Sentry\init;

class SentryErrorHandler extends ErrorHandler
{

    public $dsn;

    public function logException($exception)
    {
        parent::logException($exception); // TODO: Change the autogenerated stub
        if (!env("YII_DEBUG")) {
            init(['dsn' => $this->dsn, 'before_send' => function (\Sentry\Event $event, ?\Sentry\EventHint $hint): ?\Sentry\Event {
                if ($hint !== null && $hint->exception !== null && !$hint->exception->getCode()) {
                    return $event;
                }
                return null;
            }]);
            captureException($exception);
        }
    }
}