<?php

namespace common\components\log;

use api\helper\response\ApiConstant;
use yii\base\Component;
use function Sentry\init;

class SentryLogger extends Component
{
    public $dns;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

}