<?php

namespace api\modules\v1\frontend\article\models\search;

use api\modules\v1\frontend\article\models\Category;
use yii\data\ActiveDataProvider;

class CategorySearch extends Category
{
    public function search($params)
    {
        $query = self::find()->active();
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'params' => $params,
            ],
            'sort' => [
                'params' => $params,
            ],
        ]);
        if (!($this->load($params, "") && $this->validate())) {
            return $dataProvider;
        }
        $query->andFilterWhere([
            "slug" => $this->slug,
            "title" => $this->title,
            "body" => $this->body,
            "parent_id"=>$this->parent_id,
            "created_at" => $this->created_at,
            "status" => $this->status
        ]);
        return $dataProvider;
    }

    public function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [["slug", "title", "body", "parent_id", "status", "created_at"], "safe"],
            [["slug", "title", "body"], "string"]
        ];
    }
}