<?php

namespace common\models;

use api\modules\v1\admin\cms\models\Collection2;
use api\modules\v1\admin\cms\models\form\CollectionForm;
use common\base\cms\GetRelationCore;
use common\behaviors\JsonBehavior;
use common\models\base\ActiveRecord;
use common\models\SystemCmsCollection as SystemCmsCollectionAlias;
use common\validators\EmailValidator;
use yii\behaviors\TimestampBehavior;
use yii\db\Query;
use yii\validators\BooleanValidator;
use yii\validators\NumberValidator;
use yii\validators\SafeValidator;
use yii\validators\StringValidator;

class Collection extends ActiveRecord
{
    public $rules;
    public $jsonAttribute;
    public $slugAttribute;
    protected static $tableName = "cms_";
    protected static $schemas = [];
    const SCHEMA_COLLECTIONS = [
        [
            "name" => "title",
            "type" => "text",
            "validator" => [],
            "options" => []
        ],
        [
            "name" => "content",
            "type" => "editor",
            "validator" => [],
            "options" => []
        ],
        [
            "name" => "views",
            "type" => "number",
            "validator" => [],
            "options" => [
                "noDecimal" => true
            ]
        ],
        [
            "name" => "is_publish",
            "type" => "boolean",
            "validator" => [],
            "options" => []
        ],
        [
            "name" => "email",
            "type" => "email",
            "validator" => [],
            "options" => []
        ],
        [
            "type" => "url",
            "validator" => [],
            "options" => []
        ],
        [
            "type" => "date_time",
            "validator" => [],
            "options" => []
        ],
        [
            "type" => "file",
            "validator" => [],
            "options" => []
        ],
        [
            "name" => "user_id",
            "type" => "relation",
            "validator" => [],
            "options" => [
                "ref_table" => "",
                "ref_column" => "10"
            ]
        ],
        [
            "name" => "external_data",
            "type" => "json",
            "validator" => [],
            "options" => []
        ]
    ];
    const VALIDATOR_COLLECTIONS = [
        [
            "validator_name" => "required",
            "message_error" => "{{attribute}} is required"
        ],
        [
            "validator_name" => "min",
            "value" => 100,
            "message_error" => "{{attribute}} is min {{value}}"
        ],
        [
            "validator_name" => "max",
            "value" => 100,
            "message_error" => "{{attribute}} is max {{value}}"
        ],
        [
            "validator_name" => "unique",
            "message_error" => "{{attribute}} is unique"
        ],
        [
            "validator_name" => "file",
            "maxSize" => 10,
            "maxFile" => 20
        ]
    ];

    public function init()
    {
        $jsonAttributes = [];
        $rules = [];
        $slugAttributes = [];
        foreach (self::$schemas as $schema) {
            switch ($schema["type"]) {
                case SystemCmsCollectionAlias::TYPE_JSON:
                    $jsonAttributes[] = $schema["name"];
                    break;
                case SystemCmsCollectionAlias::TYPE_SLUG:
                    if (isset($schema["options"]["ref_column"])) {
                        $slugAttributes[$schema["name"]] = $schema["options"]["ref_column"];
                    }
                    break;
            }
            $rules[] = $this->getRuleBySchema($schema);
        }
        $this->rules = $rules;
        $this->jsonAttribute = $jsonAttributes;
        $this->slugAttribute = $slugAttributes;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            [
                "class" => JsonBehavior::class,
                "jsonAttributes" => $this->jsonAttribute
            ],
            [
                'class' => TimestampBehavior::class,
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => date("Y-m-d H:i:s"),
            ],
        ]);
    }

    public static function tableName()
    {
        return self::$tableName;
    }

    public static function setTableName($tableName)
    {
        self::$tableName = "cms_" . $tableName;
    }

    public static function setFields($schemas)
    {
        self::$schemas = $schemas;
    }

    public function getRelationCms($schema)
    {
        $options = $schema["options"];
        $collection = SystemCmsCollection::find()->where(["name" => $options["ref_table"]])->one();
        if (!$collection) {
            return [];
        }
        Collection::setFields($collection->schemas);
        Collection::setTableName($collection->name);
        if (empty($this->{$schema["name"]})) {
            return [];
        }
        $query = clone $this::find();
        $query = $query->where(["id" => explode(",", $this->{$schema["name"]})]);
        if ($options["type"] === SystemCmsCollection::TYPE_RELATION_MULTIPLE) {
            return $query->all();
        }
        return $query->one();
    }

    public function getRelationCore($schema)
    {
        /**
         * @var Query $query
         */
        $options = $schema["options"];
        $rowValues = explode(",", $this->{$schema["name"]});
        $result = new GetRelationCore([
            "tableName" => $options["ref_table"],
            "rowValues" => $rowValues,
            "type" => $options["type"]
        ]);
        return $result->result();
    }

    /**
     * @param $schema
     * @return array
     */
    public function getRuleBySchema($schema): array
    {
        $rule = [];
        switch ($schema["type"]) {
            case SystemCmsCollectionAlias::TYPE_TEXT:
            case SystemCmsCollectionAlias::TYPE_SLUG:
                $rule = [$schema["name"], StringValidator::class, "max" => 400];
                break;
            case SystemCmsCollectionAlias::TYPE_BOOLEAN:
                $rule = [$schema["name"], BooleanValidator::class];
                break;
            case SystemCmsCollectionAlias::TYPE_EMAIL:
                $rule = [$schema["name"], EmailValidator::class];
                break;
            case SystemCmsCollectionAlias::TYPE_NUMBER:
                $rule = [$schema["name"], NumberValidator::class];
                break;
            default:
                $rule = [$schema["name"], SafeValidator::class];
        }
        return $rule;
    }

    public function formName()
    {
        return "";
    }
}