<?php

namespace api\modules\v1\admin\article\models;

use Yii;
use common\models\Article as BaseArticle;
use yii\behaviors\SluggableBehavior;

class Article extends BaseArticle
{
    public function fields()
    {
        return [
            "id",
            "title",
            "body",
            "category" => "category",
            "author" => "author",
            "status",
            "created_at",
            "updated_at"
        ];
    }

    public function beforeSave($insert)
    {
        $this->created_by = Yii::$app->user->getId();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function getCategory()
    {
        return $this->hasOne(ArticleCategory::class, ["id" => "category_id"]);
    }

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors["slug"] =
            [
                'class' => SluggableBehavior::class,
                'attribute' => 'title',
                'slugAttribute' => 'slug',
            ];
        return $behaviors;
    }

    public function rules()
    {
        return array_merge(parent::rules(), [
            [["title", "body", "category_id"], "required"],
            [["thumbnail_base_url", "thumbnail_path"], "safe"],
            ["status", "default", "value" => Article::STATUS_INACTIVE]
        ]);
    }
}