<?php

namespace api\modules\v1\admin\order_return\models;

use common\models\OrderReturn as BaseOrderReturn;

class OrderReturn extends BaseOrderReturn
{
    /**
     * @var OrderReturnItem $order_return_items
     */
    public $order_return_items;

    public function fields()
    {
        return [
            "id",
            "code",
            "order" => "order",
            "office" => "office",
            "inventory" => "inventory",
            "client" => "client",
            "discount_value",
            "discount_type",
            "discount",
            "delivery_fee",
            "status",
            "quantity",
            "unit_price",
            "total_price",
            "sub_total_price",
            "created_by" => "createdBy",
            "order_return_items" => "orderReturnItems",
            "note",
            "created_at"
        ];
    }

    public function getClient()
    {
        return parent::getClient()->addSelect(["id", "name", "phone"]);
    }

    public function getOrder()
    {
        return parent::getOrder()->asArray()->select(["id", "code"]); // TODO: Change the autogenerated stub
    }

    public function getCreatedBy()
    {
        return parent::getCreatedBy()->addSelect(["id", "username"]);
    }

    public function getOffice()
    {
        return parent::getOffice()->select(["id", "name"]);
    }

    public function getInventory()
    {
        return parent::getInventory()->addSelect(["id", "name"]);
    }

    public function getOrderReturnItems()
    {
        return $this->hasMany(OrderReturnItem::className(), ["order_return_id" => "id"])->joinWith("productVariant");
    }

    public function formName()
    {
        return "";
    }

}