<?php

namespace common\components\shipping;

use common\components\shipping\models\GHNRequestObject;
use common\components\shipping\models\GHTKRequestObject;
use common\components\shipping\models\ShipperRequestBaseObject;
use common\components\shipping\shipper\GHNShipper;
use common\components\shipping\shipper\GHTKShipper;
use common\models\Order;
use common\models\OrderShip;
use yii\base\Component;
use yii\base\Exception;

/**
 * @property $httpClient
 * @property IShipper $shipperClient
 * @property ShipperRequestBaseObject $requestBaseObject
 */

class Client extends Component
{
    public $httpClient;
    /**
     * @var IShipper $shipperClient
     */
    public $shipperClient;
    /**
     * @var ShipperRequestBaseObject $requestObject
     */
    public $requestObject;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @throws Exception
     */
    public function createShipperClient(OrderShip $orderShip)
    {
        switch ($orderShip->shipper_type) {
            case GHNShipper::TYPE:
                $this->shipperClient = new GHNShipper();
                $requestObject = new GHNRequestObject();
                $requestObject->order_ship = $orderShip;
                $requestObject->loadServiceExtras();
                $this->shipperClient->init($requestObject);
                break;
            case GHTKShipper::TYPE:
                $this->shipperClient = new GHTKShipper();
                $requestObject = new GHTKRequestObject();
                $requestObject->order_ship = $orderShip;
                $requestObject->loadServiceExtras();
                $this->shipperClient->init($requestObject);
                break;
            default :
                throw new Exception("Shipper Type is not found");
        }
    }

    public function calculatorFee()
    {
        if ($this->shipperClient != null) {
            return $this->shipperClient->calculateShippingFee();
        }
        return false;
    }

    public function printBill()
    {
        if ($this->shipperClient != null) {
            return $this->shipperClient->getPrintDetail();
        }
        return false;
    }

    public function cancel()
    {
        if ($this->shipperClient != null) {
            return $this->shipperClient->cancel();
        }
        return false;
    }

    public function createOrder()
    {
        if ($this->shipperClient != null) {
            return $this->shipperClient->createOrder();
        }
        return false;
    }
}