<?php

namespace common\validators;

use Yii;
use yii\validators\Validator;

class PhoneValidator extends Validator
{
    public $message;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->message === null) {
            $this->message = Yii::t('yii', '{attribute} is not a valid phone.');
        }
    }

}