<?php

namespace api\modules\v1\frontend\feedback;

use yii\base\Module;

class FeedbackModule extends Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

}
