<?php

namespace api\modules\v1\frontend\order;

class CheckoutModule extends \yii\base\Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}