<?php

namespace common\validators\order;

use common\models\PaymentMethod;
use yii\base\DynamicModel;
use yii\validators\Validator;

class PaymentMethodValidator extends Validator
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function validateAttribute($model, $attribute)
    {
        if (empty($model->$attribute[0])) {
            $this->addError($model, $attribute, "$attribute required");
            return false;
        }
        if (!isset($model->payments)) {
            $this->addError($model, $attribute, "Payment attribute not found");
            return false;
        }
        $dynamicModel = new DynamicModel([
            "payment_method_id",
            "payment_method_name",
            "payment"
        ]);
        $dynamicModel->addRule(["payment_method_id", "payment_method_name", "payment"], "required")
            ->addRule(["payment"], "number")
            ->addRule(["payment_method_id"], "exist", ["targetClass" => PaymentMethod::className(), "targetAttribute" => ["payment_method_id" => "id"]]);
        $totalPayment = 0.0;
        foreach ($model->$attribute as $payment_method) {
            $dynamicModel->load($payment_method, "");
            if (!$dynamicModel->validate()) {
                $this->addError($model, $attribute, current($dynamicModel->getErrorSummary(true)));
                return false;
            }
            $totalPayment += $dynamicModel->payment;
        }
        if ($totalPayment !== $model->payments) {
            $this->addError($model, $attribute, "total_payment not equal payments");
        }
        return true;
    }
}