<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "administrative_unit".
 *
 * @property integer $id
 * @property string $full_name
 * @property string $full_name_en
 * @property string $short_name
 * @property string $short_name_en
 * @property string $code_name
 * @property string $code_name_en
 *
 * @property \common\models\District[] $districts
 * @property \common\models\Province[] $provinces
 * @property \common\models\Ward[] $wards
 * @property string $aliasModel
 */
abstract class AdministrativeUnit extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'administrative_unit';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id'], 'required'],
            [['id'], 'integer'],
            [['full_name', 'full_name_en', 'short_name', 'short_name_en', 'code_name', 'code_name_en'], 'string', 'max' => 255],
            [['id'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'full_name' => 'Full Name',
            'full_name_en' => 'Full Name En',
            'short_name' => 'Short Name',
            'short_name_en' => 'Short Name En',
            'code_name' => 'Code Name',
            'code_name_en' => 'Code Name En',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDistricts()
    {
        return $this->hasMany(\common\models\District::class, ['administrative_unit_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProvinces()
    {
        return $this->hasMany(\common\models\Province::class, ['administrative_unit_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWards()
    {
        return $this->hasMany(\common\models\Ward::class, ['administrative_unit_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\AdministrativeUnitQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\AdministrativeUnitQuery(get_called_class());
    }


}
