<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "cms_brand_product_sections".
 *
 * @property integer $id
 * @property string $brand
 * @property string $products
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class CmsBrandProductSection extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cms_brand_product_sections';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['created_at', 'updated_at'], 'safe'],
            [['brand', 'products'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'brand' => 'Brand',
            'products' => 'Products',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\CmsBrandProductSectionQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\CmsBrandProductSectionQuery(get_called_class());
    }


}
