<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "cms_pages".
 *
 * @property integer $id
 * @property string $slider_tops
 * @property string $banner_product_featured
 * @property string $banner_product_promotion
 * @property string $banner_product_new
 * @property string $section_products
 * @property string $search_quickly
 * @property string $search_top
 * @property string $type
 * @property string $created_at
 * @property string $updated_at
 * @property string $section_categories
 * @property string $aliasModel
 */
abstract class CmsPage extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cms_pages';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['search_quickly', 'search_top'], 'string'],
            [['created_at', 'updated_at'], 'safe'],
            [['slider_tops', 'section_products', 'section_categories'], 'string', 'max' => 255],
            [['banner_product_featured', 'banner_product_promotion', 'banner_product_new', 'type'], 'string', 'max' => 500]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'slider_tops' => 'Slider Tops',
            'banner_product_featured' => 'Banner Product Featured',
            'banner_product_promotion' => 'Banner Product Promotion',
            'banner_product_new' => 'Banner Product New',
            'section_products' => 'Section Products',
            'search_quickly' => 'Search Quickly',
            'search_top' => 'Search Top',
            'type' => 'Type',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'section_categories' => 'Section Categories',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\CmsPageQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\CmsPageQuery(get_called_class());
    }


}
