<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "cms_product_feature".
 *
 * @property string $title
 * @property string $content
 * @property double $views
 * @property integer $is_publish
 * @property string $email
 * @property string $external_url
 * @property string $publish_at
 * @property string $thumbnail
 * @property integer $user_id
 * @property string $external_data
 * @property string $aliasModel
 */
abstract class CmsProductFeature extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cms_product_feature';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['content', 'external_data'], 'string'],
            [['views'], 'number'],
            [['is_publish', 'user_id'], 'integer'],
            [['publish_at'], 'safe'],
            [['title', 'email', 'external_url'], 'string', 'max' => 500],
            [['thumbnail'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'title' => 'Title',
            'content' => 'Content',
            'views' => 'Views',
            'is_publish' => 'Is Publish',
            'email' => 'Email',
            'external_url' => 'External Url',
            'publish_at' => 'Publish At',
            'thumbnail' => 'Thumbnail',
            'user_id' => 'User ID',
            'external_data' => 'External Data',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\CmsProductFeatureQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\CmsProductFeatureQuery(get_called_class());
    }


}
