<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "cms_slider_tops".
 *
 * @property integer $id
 * @property string $thumbnail
 * @property string $link
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class CmsSliderTop extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cms_slider_tops';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['created_at', 'updated_at'], 'safe'],
            [['thumbnail', 'link'], 'string', 'max' => 500]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'thumbnail' => 'Thumbnail',
            'link' => 'Link',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\CmsSliderTopQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\CmsSliderTopQuery(get_called_class());
    }


}
