<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "cms_section_products".
 *
 * @property integer $id
 * @property string $title
 * @property string $subtitle
 * @property string $keyword
 * @property double $limit
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class CmsSectionProduct extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cms_section_products';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['limit'], 'number'],
            [['created_at', 'updated_at'], 'safe'],
            [['title', 'subtitle', 'keyword'], 'string', 'max' => 500]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'subtitle' => 'Subtitle',
            'keyword' => 'Keyword',
            'limit' => 'Limit',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\CmsSectionProductQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\CmsSectionProductQuery(get_called_class());
    }


}
