<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "cms_section_categories".
 *
 * @property integer $id
 * @property string $created_at
 * @property string $updated_at
 * @property string $category
 * @property string $brand_product_sections
 * @property string $aliasModel
 */
abstract class CmsSectionCategory extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cms_section_categories';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['created_at', 'updated_at'], 'safe'],
            [['category', 'brand_product_sections'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'category' => 'Category',
            'brand_product_sections' => 'Brand Product Sections',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\CmsSectionCategoryQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\CmsSectionCategoryQuery(get_called_class());
    }


}
