<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \common\models\DeliveryMethodQuery;

/**
 * This is the base-model class for table "delivery_method".
 *
 * @property integer $id
 * @property string $name
 * @property string $code
 * @property double $fee
 * @property integer $status
 * @property integer $is_default
 * @property integer $created_by
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 */
abstract class DeliveryMethod extends \common\models\base\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'delivery_method';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['name', 'code', 'status', 'is_default', 'created_by', 'created_at', 'updated_at', 'deleted_at'], 'default', 'value' => null],
            [['fee'], 'default', 'value' => 0],
            [['fee'], 'number'],
            [['status', 'is_default', 'created_by'], 'integer'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['name'], 'string', 'max' => 200],
            [['code'], 'string', 'max' => 100]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'name' => 'Name',
            'code' => 'Code',
            'fee' => 'Fee',
            'status' => 'Status',
            'is_default' => 'Is Default',
            'created_by' => 'Created By',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
        ]);
    }

    /**
     * @inheritdoc
     * @return DeliveryMethodQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new DeliveryMethodQuery(static::class);
    }
}
