<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use \common\models\FeedbackQuery;

/**
 * This is the base-model class for table "feedback".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $subject
 * @property string $title
 * @property string $fullname
 * @property string $phone
 * @property string $email
 * @property string $content
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property integer $is_confirm_term
 */
abstract class Feedback extends \common\models\base\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'feedback';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['user_id', 'subject', 'title', 'fullname', 'phone', 'email', 'content', 'status', 'created_at', 'updated_at', 'deleted_at'], 'default', 'value' => null],
            [['is_confirm_term'], 'default', 'value' => 0],
            [['user_id', 'status', 'is_confirm_term'], 'integer'],
            [['content'], 'string'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['subject', 'title', 'fullname', 'email'], 'string', 'max' => 255],
            [['phone'], 'string', 'max' => 50]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'user_id' => 'User ID',
            'subject' => 'Subject',
            'title' => 'Title',
            'fullname' => 'Fullname',
            'phone' => 'Phone',
            'email' => 'Email',
            'content' => 'Content',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'is_confirm_term' => 'Is Confirm Term',
        ]);
    }

    /**
     * @inheritdoc
     * @return FeedbackQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new FeedbackQuery(static::class);
    }
}
