<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "history_log".
 *
 * @property integer $id
 * @property integer $level
 * @property string $category
 * @property double $log_time
 * @property string $prefix
 * @property string $message
 * @property string $old_data
 * @property string $new_data
 * @property string $tag
 * @property string $aliasModel
 */
abstract class HistoryLog extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'history_log';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['level'], 'integer'],
            [['log_time'], 'number'],
            [['old_data', 'new_data'], 'string'],
            [['category', 'prefix', 'message', 'tag'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'level' => 'Level',
            'category' => 'Category',
            'log_time' => 'Log Time',
            'prefix' => 'Prefix',
            'message' => 'Message',
            'old_data' => 'Old Data',
            'new_data' => 'New Data',
            'tag' => 'Tag',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\HistoryLogQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\HistoryLogQuery(get_called_class());
    }


}
