<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "order_order_return".
 *
 * @property integer $id
 * @property integer $status
 * @property integer $order_id
 * @property integer $order_return_id
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property string $aliasModel
 */
abstract class OrderOrderReturn extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'order_order_return';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['status', 'order_id', 'order_return_id'], 'integer'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'status' => 'Status',
            'order_id' => 'Order ID',
            'order_return_id' => 'Order Return ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\OrderOrderReturnQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\OrderOrderReturnQuery(get_called_class());
    }


}
