<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "order_discount".
 *
 * @property integer $id
 * @property integer $order_id
 * @property integer $type_id
 * @property string $type
 * @property string $code
 * @property string $title
 * @property integer $discount_type
 * @property double $discount_value
 * @property double $discount_price
 * @property string $offices
 * @property string $condition_items
 * @property string $condition_type
 * @property integer $apply_for_all
 * @property double $order_total_required
 * @property integer $limit
 * @property integer $used
 * @property string $extras_fields
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class OrderDiscount extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'order_discount';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['order_id', 'type_id', 'discount_type', 'apply_for_all', 'limit', 'used'], 'integer'],
            [['discount_value', 'discount_price', 'order_total_required'], 'number'],
            [['offices', 'condition_items', 'extras_fields'], 'string'],
            [['created_at', 'updated_at'], 'safe'],
            [['type', 'code', 'title', 'condition_type'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'order_id' => 'Order ID',
            'type_id' => 'Type ID',
            'type' => 'Type',
            'code' => 'Code',
            'title' => 'Title',
            'discount_type' => 'Discount Type',
            'discount_value' => 'Discount Value',
            'discount_price' => 'Discount Price',
            'offices' => 'Offices',
            'condition_items' => 'Condition Items',
            'condition_type' => 'Condition Type',
            'apply_for_all' => 'Apply For All',
            'order_total_required' => 'Order Total Required',
            'limit' => 'Limit',
            'used' => 'Used',
            'extras_fields' => 'Extras Fields',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\OrderDiscountQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\OrderDiscountQuery(get_called_class());
    }


}
