<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "order_return_item".
 *
 * @property integer $id
 * @property integer $office_id
 * @property integer $inventory_id
 * @property integer $order_return_id
 * @property integer $quantity
 * @property double $unit_price
 * @property double $sub_total_price
 * @property double $total_price
 * @property double $discount_value
 * @property integer $discount_type
 * @property double $discount
 * @property integer $status
 * @property integer $product_id
 * @property integer $product_variant_id
 * @property string $note
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property string $aliasModel
 */
abstract class OrderReturnItem extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'order_return_item';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['office_id', 'inventory_id', 'order_return_id', 'quantity', 'discount_type', 'status', 'product_id', 'product_variant_id'], 'integer'],
            [['unit_price', 'sub_total_price', 'total_price', 'discount_value', 'discount'], 'number'],
            [['note'], 'string'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'office_id' => 'Office ID',
            'inventory_id' => 'Inventory ID',
            'order_return_id' => 'Order Return ID',
            'quantity' => 'Quantity',
            'unit_price' => 'Unit Price',
            'sub_total_price' => 'Sub Total Price',
            'total_price' => 'Total Price',
            'discount_value' => 'Discount Value',
            'discount_type' => 'Discount Type',
            'discount' => 'Discount',
            'status' => 'Status',
            'product_id' => 'Product ID',
            'product_variant_id' => 'Product Variant ID',
            'note' => 'Note',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\OrderReturnItemQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\OrderReturnItemQuery(get_called_class());
    }


}
