<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "order_return".
 *
 * @property integer $id
 * @property integer $client_id
 * @property string $code
 * @property integer $order_id
 * @property double $discount_value
 * @property integer $discount_type
 * @property double $discount
 * @property double $delivery_fee
 * @property string $data_delivery_fee
 * @property string $other_fee
 * @property integer $status
 * @property string $progress_status
 * @property integer $quantity
 * @property double $unit_price
 * @property double $total_price
 * @property double $payments
 * @property double $sub_total_price
 * @property integer $created_by
 * @property string $note
 * @property integer $office_id
 * @property integer $inventory_id
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property string $aliasModel
 */
abstract class OrderReturn extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'order_return';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['client_id', 'order_id', 'discount_type', 'status', 'quantity', 'created_by', 'office_id', 'inventory_id'], 'integer'],
            [['discount_value', 'discount', 'delivery_fee', 'unit_price', 'total_price', 'payments', 'sub_total_price'], 'number'],
            [['data_delivery_fee', 'other_fee', 'progress_status', 'note'], 'string'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['code'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'client_id' => 'Client ID',
            'code' => 'Code',
            'order_id' => 'Order ID',
            'discount_value' => 'Discount Value',
            'discount_type' => 'Discount Type',
            'discount' => 'Discount',
            'delivery_fee' => 'Delivery Fee',
            'data_delivery_fee' => 'Data Delivery Fee',
            'other_fee' => 'Other Fee',
            'status' => 'Status',
            'progress_status' => 'Progress Status',
            'quantity' => 'Quantity',
            'unit_price' => 'Unit Price',
            'total_price' => 'Total Price',
            'payments' => 'Payments',
            'sub_total_price' => 'Sub Total Price',
            'created_by' => 'Created By',
            'note' => 'Note',
            'office_id' => 'Office ID',
            'inventory_id' => 'Inventory ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\OrderReturnQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\OrderReturnQuery(get_called_class());
    }


}
