<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "order_promotion".
 *
 * @property integer $id
 * @property integer $order_id
 * @property integer $promotion_id
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class OrderPromotion extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'order_promotion';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['order_id', 'promotion_id'], 'integer'],
            [['created_at', 'updated_at'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'order_id' => 'Order ID',
            'promotion_id' => 'Promotion ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\OrderPromotionQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\OrderPromotionQuery(get_called_class());
    }


}
