<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "system_cms_collection".
 *
 * @property integer $id
 * @property string $name
 * @property integer $user_id
 * @property string $schemas
 * @property string $indexs
 * @property integer $type
 * @property integer $status
 * @property string $list_rule
 * @property string $view_rule
 * @property string $create_rule
 * @property string $update_rule
 * @property string $delete_rule
 * @property string $options
 * @property string $external_data
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class SystemCmsCollection extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'system_cms_collection';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'type', 'status'], 'integer'],
            [['schemas', 'indexs', 'list_rule', 'view_rule', 'create_rule', 'update_rule', 'delete_rule', 'options', 'external_data'], 'string'],
            [['created_at', 'updated_at'], 'safe'],
            [['name'], 'string', 'max' => 200]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'user_id' => 'User ID',
            'schemas' => 'Schemas',
            'indexs' => 'Indexs',
            'type' => 'Type',
            'status' => 'Status',
            'list_rule' => 'List Rule',
            'view_rule' => 'View Rule',
            'create_rule' => 'Create Rule',
            'update_rule' => 'Update Rule',
            'delete_rule' => 'Delete Rule',
            'options' => 'Options',
            'external_data' => 'External Data',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\SystemCmsCollectionQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\SystemCmsCollectionQuery(get_called_class());
    }


}
