<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "tag".
 *
 * @property integer $id
 * @property string $name
 * @property string $slug
 * @property string $type
 * @property integer $popularity
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class Tag extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tag';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'slug', 'type'], 'required'],
            [['popularity'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['name', 'slug', 'type'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'slug' => 'Slug',
            'type' => 'Type',
            'popularity' => 'Popularity',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\TagQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\TagQuery(get_called_class());
    }


}
