<?php

namespace api\modules\v1\admin\order\models\form;

use common\components\log\BuildLogDbTarget;
use common\components\log\DbTarget;
use common\validators\order\PaymentMethodValidator;
use api\modules\v1\admin\order\models\Order;
use Throwable;

class UpdateOrderAfterCheckoutForm extends Order
{
    public $payment_methods;

    public function rules()
    {
        return [
            ["note", "string"],
            ["status", "in", "range" => [Order::STATUS_DONE]],
            ["payment_methods", PaymentMethodValidator::className()],
        ];
    }

    /**
     * @throws Throwable
     */
    public function afterSave($insert, $changedAttributes)
    {
        if (!empty($changedAttributes)) {
            (new BuildLogDbTarget())->push("Update Order After Checkout", __METHOD__, DbTarget::TAG_UPDATED, $this->getAttributes(), $this->getOldAttributes());
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

}