<?php

namespace api\modules\v1\admin\order_return\models\form;

use api\modules\v1\admin\order_return\models\OrderReturnItem;
use common\models\Inventory;
use common\models\Order;
use common\models\OrderItem;

/**
 * @property Order $order
 */
class OrderReturnItemForm extends OrderReturnItem
{
    public $order;

    public function beforeSave($insert)
    {
        if ($insert) {
            $this->office_id = $this->order->office_id;
            $this->status = OrderReturnItem::STATUS_ACTIVE;
            /**
             *  Case Order pos inventory with null, inventory_id is inventory first in offices
             */
            $this->inventory_id = $this->order->inventory_id;
            if (!$this->order->inventory_id) {
                $inventory = Inventory::find()->where(["office_id" => $this->order->office_id])->one();
                $this->inventory_id = $inventory->id;
            }
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [["order_return_id", "quantity", "product_variant_id", "product_id"], "required"],
            [["quantity"], "quantityValidator"],
            [["quantity"], "integer", "min" => 1],
            [["unit_price", "sub_total_price", "total_price"], "number", "min" => 1],
            ["note", "string"],
            ["product_variant_id", "productVariantValidator"]
        ];
    }

    public function quantityValidator($attribute)
    {
        $quantityReturned = $this->getQuantityReturnEdByOrderId($this->order->id);
        $quantityOrderItem = $this->getQuantityOrderItemByOrderId($this->order->id);
        if ($this->quantity > ($quantityOrderItem - $quantityReturned)) {
            $this->addError($attribute, "Quantity invalid");
        }
    }

    public function productVariantValidator($attribute)
    {
        $orderItem = OrderItem::find()->where([
            "product_variant_id" => $this->product_variant_id,
            "order_id" => $this->order->id
        ])->one();
        if (!$orderItem) {
            $this->addError($attribute, "Product Variant not found");
        }
    }
}