<?php

namespace api\modules\v1\frontend\comment;

class CommentModule extends \yii\base\Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}